### ISSUE TITLE
Integrating own benchmarks

### ISSUE THREAD

**Issue by mkatsa** [lpentecost/NVMExplorer#2]
Hello,

I have successfully installed and executed the NVMexplorer toolset. I would like to ask if there is any extra documentation to be added on how we can integrate our own benchmarks for evaluation and exploration.

Thanks

**Comment by lpentecost** [comment]
Thank you for your question!  There are two ways to specify your own input benchmark either by 

(1) directly inputing the read/write access characteristics of a given benchmark in the configuration file using the `read_frequency`, `write_frequency`, `read_size`, and `write_size` input parameters, (you can also use a list of read/write frequency values to specify a list of benchmarks) or 
(2) modify / duplicate one of the `workload_data` files in data/workload_data according to input a set of benchmarks at once.

For details and examples, you can also refer to our [ISCA 2022 tutorial](https://www.youtube.com/watch?v=9rXI7MIMxwo&t=14s) at around minute 44:00.
